services:
  meeting-transcription-agent:
    container_name: meeting-transcription-agent
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WHISPER_MODEL_SIZE=${WHISPER_MODEL_SIZE:-base}
      - LOG_LEVEL=INFO
    volumes:
      # Mount data directory for transcriptions
      - /DATA/san-raid5/AppData/meeting-transcription-agent/data:/app/host-data
    # user: "1000:1000"  # Removed - container starts as root to fix permissions, then switches to 1000:1000
    # restart: unless-stopped  # MCP servers should exit when no client is connected
    healthcheck:
      # Simple healthcheck that verifies dependencies are available
      test: ["CMD", "python", "-c", "import faster_whisper; print('Dependencies OK')"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 30s
