services:
  fast-whisper-mcp:
    image: ghcr.io/mkadrlik/meeting-transcription-agent:latest
    container_name: fast-whisper-mcp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WHISPER_MODEL_SIZE=${WHISPER_MODEL_SIZE:-base}
      - LOG_LEVEL=INFO
    volumes:
      # Mount data directory for transcriptions
      - /DATA/san-raid5/AppData/meeting-transcription-agent/data:/app/data
      # Mount cache directory for models
      - /DATA/san-raid5/AppData/meeting-transcription-agent/cache:/app/.cache
    user: "1000:1000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "from faster_whisper import WhisperModel; print('Fast Whisper ready')"]
      interval: 30s
      timeout: 10s
      retries: 3