version: '3.8'

services:
  meeting-transcription-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting-transcription-agent
    volumes:
      - ./transcriptions:/app/transcriptions
    devices:
      - /dev/snd:/dev/snd
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true