services:
  meeting-transcription-agent:
    container_name: meeting-transcription-agent
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WHISPER_MODEL_SIZE=${WHISPER_MODEL_SIZE:-base}
      - LOG_LEVEL=INFO
    volumes:
      # Mount data directory for transcriptions
      - /DATA/san-raid5/AppData/meeting-transcription-agent/data:/app/host-data
    # user: "1000:1000"  # Removed - container starts as root to fix permissions, then switches to 1000:1000
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "from faster_whisper import WhisperModel; print('Meeting Transcription Agent ready')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
